### ISSUE TITLE
Test upload and download speed to o!rdr server on setup

### ISSUE THREAD

**Issue by dragongoose** [MasterIO02/ordr-client#3]
This could be helpful to new renderers so they know how fast their connection to the server is, and give more info for client acceptance.

Possibly also give recommendation about their speed? Such as if it is slow, warn that the client most likely wont receive a lot of renders.

I'd be glad to make a PR about this too,

**Comment by MasterIO02** [comment]
yeah, that's something I had in mind to add, but idk how it could be implemented, currently there's a librespeed server (https://speedtest.issou.best) and nperf server running on the o!rdr server but I'm not sure if there's node packages allowing to run a speedtest to those servers type.
It would probably need to send some speedtest results to the o!rdr server too

**Comment by dragongoose** [comment]
librespeed has a CLI version too, https://github.com/librespeed/speedtest-cli). I bet we could spawn it using `child_process` and just grab the results from stdout. 

I used this local json file to connect to o!rdr librespeed instance.
```json

[
  {
    "id": 1,
    "name": "o!rdrFR",
    "server": "https://st1.issou.best/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  }
]
```

**Comment by dragongoose** [comment]
Just came to my mind, instead of getting upload download speed with librespeed, the client could send the benchmark beatmap to the server, and base the user's upload speed off of that?
